### ISSUE TITLE
Mac OS App is not showing the status code

### ISSUE THREAD

**Issue by NandoSalvaterra** [yagiz/Bagel#53]
I was using the Bagel Mac OS app since January and now, when a request is completed, it does not show the status code anymore

<img width="1094" alt="bug_bagel" src="https://user-images.githubusercontent.com/13475039/65606107-a7785580-df80-11e9-8dac-79efae8812d4.png">

**Comment by okankurtulus** [comment]
I think there is a compatibility issue with Xcode 11, lower versions didn't have this issue. Possible in next builds it will be ok

**Comment by ws513** [comment]
it is related to iOS 13, if your device is iOS 12 or lower it works fine

**Comment by ShotaKashihara** [comment]
I fixed this problem. If this Pull Request (#56) is merged, the status code will be show.
If you can't wait for the merge, you can use the following fork.
```
pod 'Bagel', :git => 'https://github.com/ShotaKashihara/Bagel'
```

**Comment by yagiz** [comment]
@ShotaKashihara Awesome! 

I'll accept PR as soon as possible.

**Comment by mohpor** [comment]
I have built the app from source (latest) and it still doesn't show status code for iOS 13+ devices. I have checked my git and I can confirm that the PR (#56) is merged in my local repo.

**Comment by mohpor** [comment]
My Bad, you actually have to update the iOS version not the mac app. In my case, (because the Pod has not been pushed to new version) I have pointed my pod to master branch of this repository and the problem is fixed.

**Comment by alexn7** [comment]
> My Bad, you actually have to update the iOS version not the mac app. In my case, (because the Pod has not been pushed to new version) I have pointed my pod to master branch of this repository and the problem is fixed.

I tried the same thing but it still doesn't work, do I need to do other in addition to make it work? This is what I've put in the Podfile:

pod 'Bagel', :git => 'https://github.com/yagiz/Bagel.git', :branch => 'master'

when I do a pod install, I see "installing Bagel 1.3.2", but I think it isn't correct

**Comment by mohpor** [comment]
Not really, as far as I remember it stopped working after some iOS updates. I'm using Swift Package Manager now and it works.

**Comment by omelnik** [comment]
This issue is reproducible for me. The status codes are still not shown.
Any suggestions how to fix this issue?

**Comment by Tawfikk** [comment]
This issue still actual ... @yagiz

**Comment by yagiz** [comment]
This issue should be fixed with 1.4.0
